#!/bin/bash -e

ORG_PATH="github.com/gebi"
REPO_PATH="${ORG_PATH}/passhash"

export GOPATH=${PWD}/gopath

rm -f $GOPATH/src/${REPO_PATH}
mkdir -p $GOPATH/src/${ORG_PATH}
ln -s ${PWD} $GOPATH/src/${REPO_PATH}

eval $(go env)

go build -o passhash ${REPO_PATH}
